# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc16fcba51f0d2f36a9360cd45862d4a1e5ced606c9335de4e3f6c437b09be595cbf102b20dd3752b6adf9f2be602b3977912b7d28b4dd1066ce70b5cb3d8719

test:
  secret_key_base: 215fa9a8dc3d4c619297e7c8ae634239ee3ad814690d2d309952635f057f40ea0c58ecaa51a1e838b3f463f4c1788a8084ee7ecaf4acd3aad0ca1290e2badc1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
